version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: holy_user
      POSTGRES_PASSWORD: uynr12ke56uaWk9vfYyQD5eBepPnrYEs
      POSTGRES_DB: holy_db
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: holy_user
      POSTGRES_PASSWORD: uynr12ke56uaWk9vfYyQD5eBepPnrYEs
      POSTGRES_DB: holy_db
      SIGN_IN_TOKEN_SECRET: tatat
      DATABASE_HOST: dpg-chuunendvk4oliu0g4t0-a.frankfurt-postgres.render.com
      DATABASE_PORT: 5432
      DATABASE_USERNAME: holy_user
      DATABASE_NAME: holy_db
      DATABASE_PASSWORD: uynr12ke56uaWk9vfYyQD5eBepPnrYEs
    ports:
      - '8080:3000'
    volumes:
      - .:/app
