version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: doadmin
      POSTGRES_PASSWORD: AVNS_cazWzMhL8fUb9RsQV5M
      POSTGRES_DB: defaultdb
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: doadmin
      POSTGRES_PASSWORD: AVNS_cazWzMhL8fUb9RsQV5M
      POSTGRES_DB: defaultdb
      SIGN_IN_TOKEN_SECRET: tatat
      DATABASE_HOST: db-postgresql-fra1-23515-do-user-13296757-0.b.db.ondigitalocean.com
      DATABASE_PORT: 5432
      DATABASE_USERNAME: doadmin
      DATABASE_NAME: defaultdb
      DATABASE_PASSWORD: AVNS_cazWzMhL8fUb9RsQV5M
    ports:
      - '8080:3000'
    volumes:
      - .:/app