version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: holy_user
      POSTGRES_PASSWORD: holy_pass
      POSTGRES_DB: holy_db
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: holy_user
      POSTGRES_PASSWORD: holy_pass
      POSTGRES_DB: holy_db
      SIGN_IN_TOKEN_SECRET: tatat
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: holy_user
      DATABASE_NAME: holy_db
      DATABASE_PASSWORD: holy_pass
    ports:
      - '8080:3000'
    volumes:
      - .:/app